apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AzwfdQVHEyxYY8pMBUk6idASyQ2eIGNTFxPQ3yklZmhSFw7vZNLxnA==,iv:o8WkscS+32wPojEc6n3grG5HFJ+xocnfI6Z8rXUzfpM=,tag:yq0S31JYpmirNRPHCgmzZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wv7u7talmyntfs9exl6pgypwrtpqwy3wzfzg46qwc6sqhh9zr5gq3hsnzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa1F3UDA3eGpvNnRjemd6
            ajdSeWQ3VnVLRjF0S2h0VWY0OEQzWXJVQnlzCnBpZm0wUGpGUkZJUWtianM3ZElP
            WVV0V2ZmRnZ5bHA5RmE0WG5vbWpGUUUKLS0tIEtxNitHMHF4WWdpZDdvZGJMZGpE
            MHNRdWNxdHBsZjUrVWtqMitya1ZDZlkKdv4E1ZUuJf8Z1bCD4jPDEmWA+GHunmDC
            hs+HgLScDiwlUpJ7RjjiXn5tDNh4gPMT5c+eOm4rfjuG/CxBDg6rCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T16:58:10Z"
    mac: ENC[AES256_GCM,data:9V1IOK0okh9rsc6AJezoGRzKZJuNqakDhCnny5aLRkmbopLoo+1e1fZNngTqtlBG2GMLu1YxX0k7ducKa2TbLx0L1LGrnMRCwA29VTsBP+zb2/+CHgKtFWVdyO3Kz+tAlOpKzdGZ7YDQl0C3sqDD9GT4aL9zptvebdjijfkHtz8=,iv:uDcs0uTbVToQS0PwePuQDw3BefGKpWUBnbyiPDGYEXM=,tag:TPw/kd+cYLyY/ysRUp4drg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
