---
apiVersion: v1
kind: Service
metadata:
  name: homecluster-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homecluster.bakernet.casa
    io.cilium/lb-ipam-ips: 10.0.1.50
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: homecluster
    role: primary
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-r
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     cnpg.io/podRole: instance
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-ro
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     role: replica
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-rw
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     role: primary
#   sessionAffinity: None
