---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: authentik-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_REDIS_PASSWORD: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: /bakerkubes/authentik

