---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.4@sha256:f44e91787b843612a3878d8d8fae227b9db63f471214314f5b2e73576ca633d0
            env:
              REDIS_REPLICATION_MODE: master
            resources:
              requests:
                cpu: 5m
                memory: 256M
              limits:
                memory: 256M
    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379
