apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bTqGG1Z4jl5EKKvVAor0EqgI6jrJXBBkzkraaRz6JbFTy+Jf,iv:l64FpD99GcLzLHn/eidHkk8v4a4Lodi6tyLqPnKRe5c=,tag:Cyk3ghHkf0hTV0QDoROGOA==,type:str]
    credentials.json: ENC[AES256_GCM,data:kA9IkKMja9+ED2A6Ogqx7WkD81WmsfzqgFa9Tr2iOqwsB6/8wT6fhfBh3ib2hKNeaFvTFOI3yod0C+Chlp8pWbh391JbgRJ3XM16K9d0DtPBL6z5fQ02997su4AUYn1Os4B3INdUPYvHb0D/6vIRCyhY4MdzqcgepEUmWgg/KQWcyOZaBTkMkEqGrP2mrI9GLHlKyI69NMN1RRnax6ORjBJk9wjNtFQasgTLkuXDcA==,iv:j2A0g8ucLKd9dfLBUeYUm9jwiRxnD2tL9UjyOye1z/8=,tag:UyG5Vh0Lsmjj+UguSplJlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw5ntjd9l7lllxkam9aew2sz3483vaeuz7dx3ne798dqpm0hdlsv8px8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQTVyaHBFS2REWmRCVFQr
            YU56Wjdwa2d5K2l4YlNROWwyTkYwaEs1aHdrCmZld0V0elVrNmI1MTU3dGFSdlBu
            YWFLZndsSVJSTzNBVExlVWZwakpoMG8KLS0tIGd3Tk1kYkU2dDRzTjdQRTRJQ1Ri
            V3pwYTk1SEl3R1VrZStJL2NKZzhlVmMKskV9JDCc1laIsSnQ+LNPm1kfS0a2td5w
            Xqometc8dyZ2dO5MtBEvkSjyFaRiCsTY+FY1NS/C2xDrs4b0cIIXGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T09:22:43Z"
    mac: ENC[AES256_GCM,data:m3o0xd8AH73SarcvXKy47JCI+MzZy9WZxOOvQYmJi4+5Um5JGySfcuH9NY/3CdviIkLZ65LT5rPVfA82OfFqZ373A21n+Cdeeorao8D+G167NGWRAmUK2YpdATX/sm4WTF4z6JEqUU9OHPln5U9sWetdpFZwek9va5e1/R6mMTw=,iv:/mWjFPXnXDdCuVeUAEleNb+SchJlJ103ArG+eG73UZY=,tag:3acV+Z0/sg88+xNCZWrQuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
