---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_ENGINE: postgres
        POSTGRES_USER: &dbUser "{{ .MEALIE__POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE__POSTGRES_PASSWORD }}"
        POSTGRES_SERVER: &dbHost homecluster-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &database mealie
        INIT_POSTGRES_DBNAME: *database
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /bakerkubes/mealie
    - extract:
        key: /bakerkubes/cloudnative-pg
