---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name mealie
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.0.0-RC2@sha256:9881b16dda92272c6eeeb132697ad2379be1c562f0f53f86f20ce2654b57f455
            env:
              BASE_URL: &url mealie.bakernet.casa
              ALLOW_SIGNUP: 'false'
              TZ: Europe/London
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: &port 9000

    ingress:
          main:
            enabled: true
            className: external
            annotations:
              external-dns.alpha.kubernetes.io/target: external.bakernet.casa
              hajimari.io/enable: "true"
              hajimari.io/icon: mdi:food-variant
            hosts:
              - host: &host "{{ .Release.Name }}.bakernet.casa"
                paths:
                  - path: /
                    service:
                      name: main
                      port: http
            tls:
              - hosts:
                  - *host
    persistence:
      config:
        enabled: true
        existingClaim: mealie-config
        globalMounts:
          - name: data
            mountPath: /app/data
