---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config
  namespace: home
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
