---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: restic-nas-prune
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: restic-nas
      namespace: network
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/mazzolino/restic
              tag: latest
            # https://github.com/djmaze/resticker#configuration-options
            env:
              TZ: Europe/London
              PRUNE_CRON: "0 45 3 * * *"  # 3:45am every day
              RESTIC_REPOSITORY: s3:s3.eu-central-003.backblazeb2.com/bakernet-nas
              # PRE_COMMANDS: |-
              #   curl -fsS -m 10 --retry 5 -o /dev/null "http://healthchecks.monitoring.svc.cluster.local/ping/${HEALTHCHECKS_RESTIC_REMOTE_PRUNE_UUID}/start"
              # POST_COMMANDS_FAILURE: |-
              #   curl -s -d "The remote restic prune failed" -H "Title: Backups" -H "Tags: rotating_light" "http://ntfy.comms.svc.cluster.local/homelab"
              #   curl -fsS -m 10 --retry 5 -o /dev/null "http://healthchecks.monitoring.svc.cluster.local/ping/${HEALTHCHECKS_RESTIC_REMOTE_PRUNE_UUID}/fail"
              # POST_COMMANDS_SUCCESS: |-
              #   curl -fsS -m 10 --retry 5 -o /dev/null "http://healthchecks.monitoring.svc.cluster.local/ping/${HEALTHCHECKS_RESTIC_REMOTE_PRUNE_UUID}"
            envFrom:
              - secretRef:
                  name: restic-secret
    service:
      main:
        enabled: false
