---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-config
  namespace: security
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
