---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  namespace: security
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      # role: arn:aws:iam::123456789012:role/external-secrets
      region: eu-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-connect-token
            key: access-key
            namespace: security
          secretAccessKeySecretRef:
            name: aws-ssm-connect-token
            key: access-key-secret
            namespace: security