apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3JVFXyPdHToLymAsXRaP47PeyNkh7BEFZvHHEX/4eXPM4xbtrgtF1Q==,iv:6c7feE3JyPTQKqAELxbqPPNPhs18eaSZYp7OMvF3+WA=,tag:WOHNRaaUcfR1OwuTs+/TbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw5ntjd9l7lllxkam9aew2sz3483vaeuz7dx3ne798dqpm0hdlsv8px8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RmtyY3Z0V2dyYUdPNUJ1
            U1k0WThNcFBpNXJmK0lCSzRNRGR0NmRFNHpvClhyaUE4R0tXRG9oSEdqVjFXUHJL
            bFVjMjlUTHRob0pzN2RsOUxySXEyWkkKLS0tIG82LzNlZGptQTczbjcyWHRINnJK
            Y3RzTXlEQ1htTTA5cmlMUGZKQXRoVzAKl9ZI3tqpSIl/rSFssf+jKkkHJqt/EmCK
            PENpsauSI7r8n6xcX3nfkBht7FnKftq4ANT49FC3c3CdKJ5PihNpEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T09:55:13Z"
    mac: ENC[AES256_GCM,data:P4uK6J08y5jRYtW71XDWfhlb24sqXqZ5txwD+eEUI7NBqCJtM3ZhMfHQqMOOCCxy6J9y1zsjAETpDPJVqKIwDGXtEJGY5lj/CiC+sm75fghv4lVYzNipOyODN0R+Q3nc4i4gWTM4nTuQPGkWSIVz8KSTJ5XPaKPZwtQHX6drw3s=,iv:vtt7yYO5c4SF8boMEy+hBnJGt2QauhNuM1g1gtNvd+8=,tag:BZ1twuBVD64WF2t+fvL3fA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
