apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:O/vcWnLTOMaEfmtsx0dzcgrpHABR4QH2q/lXDswAEZ2vQbXoFvcsYw==,iv:B7AMtXf/SQofw4/pRfrZBPASWlC9P5uNmbDUxZkrWN4=,tag:amfR+TANBXPUliMueAb8WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw5ntjd9l7lllxkam9aew2sz3483vaeuz7dx3ne798dqpm0hdlsv8px8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSzhxMnMxQ0QvdTljNDJy
            TUxZak5uUThNM1Fwbi9FejNCNGhDMjBPWUZJCmF0a1J6SFFBNWxIc1FaUTRsZXJh
            WG1XYXZPcTV3VlEydlhaMDVva1NXQnMKLS0tIDlSSU9mdDQ0S0o5UGI0UTBTa0FB
            N3MvQm55ZE5GOXNoOWZzNWV1NG9KT1EKIcIpwXDFwYbgXlxB8tu6WJr4lBC2glEU
            LxqeoBFVCeDrRsyrlUlp7d1feP4GM/8mV387vYEE9EYvCoayJ6q2Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T09:22:43Z"
    mac: ENC[AES256_GCM,data:HAOaGy5ASpKul2b9XYU7xggiy+ycy4zY70EkJycQlnME4bRmUuYxJIc3lMGIEK/kisVQJaa3PJ82QP8ziYUdigcDnMtfy6AyWChJuxYthqvyGy98dhnKzCu5VGau1ph6x/OPsLw80gqxFc4rmmP+1qOiiKxhZNXMsq0rpHMKExY=,iv:d1PBokKs+BL6HmmauPbvCd3V1aO0GJR/sk/hI3I+Unc=,tag:fOe0ygbXXvdQ+eMV1QQMjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
