---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .BACKBLAZE_KEYID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .BACKBLAZE_APPKEY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_KEY }}"
        NAS_BACKUP_HEALTHCHECKS_URL: "{{ .NAS_HEALTHCHECKS_URL }}"
        S3_BACKUP_HEALTHCHECKS_URL: "{{ .S3_HEALTHCHECKS_URL }}"
        PVC_BACKUP_HEALTHCHECKS_URL: "{{ .PVC_HEALTHCHECKS_URL }}"
  dataFrom:
    - extract:
        key: /bakerkubes/restic
    - extract:
        key: /bakerkubes/backblaze

