---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  #PVC Backup
  - ./pvc_backup/pvc_backup.yaml
  - ./pvc_backup/pvc_prune.yaml
  - ./pvc_backup/pvc_check.yaml
  #NAS backup
  - ./nas_backup/nas_backup.yaml
  - ./nas_backup/nas_prune.yaml
  - ./nas_backup/nas_check.yaml
  #S3 backup
  - ./s3_backup/s3_backup.yaml
  - ./s3_backup/s3_prune.yaml
  - ./s3_backup/s3_check.yaml
