---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname givtcp
  namespace: flux-system
spec:
  targetNamespace: home
  dependsOn:
    - name: mosquitto
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  path: "./kubernetes/apps/home/givtcp/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
