---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: healthchecks
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: healthchecks-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # email steup
        DEFAULT_FROM_EMAIL: "{{ .EMAIL_FROM_ADDRESS}}"
        EMAIL_HOST: "{{ .SMTP_SERVER}}"
        EMAIL_PORT: "{{ .SMTP_TLS_PORT }}"
        EMAIL_HOST_USER: "{{ .SMTP_SUPERUSER }}"
        EMAIL_HOST_PASSWORD: "{{ .SMTP_SUPERUSER_PASSWORD }}"
        EMAIL_USE_TLS: "True"
        PUSHOVER_SUBSCRIPTION_URL: "{{ .PUSHOVER_SUBSCRIBE_URL }}"
        PUSHOVER_API_TOKEN: " {{ .PUSHOVER_API_KEY}}"
  dataFrom:
    - extract:
        key: /bakerkubes/email
    - extract:
        key: /bakerkubes/healthchecks
---
