---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthchecks-config
  namespace: monitoring
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
