---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dbms
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: servers-json
    files:
      - ./resources/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
