apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:imdD2fsxkpmCD9COX96ldHTg0HT0q80nOsyzbyawlR8=,iv:AUlTDRt2fv3bzxXV2Hld+e2+T2Me/qX2UG45SR9Y/II=,tag:kxvg1c4CXRJuGAyxdgn4LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xhw5ntjd9l7lllxkam9aew2sz3483vaeuz7dx3ne798dqpm0hdlsv8px8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZEZWNXM1MDVUNVpmcHBL
            Mnk4R1k3a1k3M3NXTlcrd2V4dVlkMTgvVnhFCks2OFphTEc4bEVnbWNjM00wUGpu
            Wkh1Z2p2aTQySHBWanBSQnRsQ1dLcTAKLS0tIDc4MGIydEFrU3pTQjh0aUFzUXo4
            UGJQZFBVQjdLNnVDS2ZKdFBORVRmdWcKAiF8uskCVtM1VVgXH/9htFSj/putq7ZO
            wsjAptyVl4WcSA7Ex0u1Id4TbEB3oXmzKV02J9puBbD5eYdNxm+aUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T09:55:13Z"
    mac: ENC[AES256_GCM,data:v9Fbaw4+r7cs/X15XmeVb8NIM5uV9LkeG2AVDRQeVk8Jtiqv3WGxOJyVz4SsBcZpdDJx4ETi927ZPhQpt3cddUN9OzDspfn8CTFTTJ6LPuOQR5enjleQtMXV3HGpDrKFSjTJl8jqlR1h6AUhIUAwaosVZo8Hm2f39r4RGYz4amY=,iv:vkLhRPNUBOs7/HBKuvqIO6FNhO6S86jmamScFojuLiA=,tag:H0tghBSOmx7xxrZoQiae2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
